version: '3'
services:
  angular-app:
    build:
      context: ./frontend
    image: frontend:latest
    ports:
      - "4200:4200"
    depends_on:
      - nodejs-app

  nodejs-app:
    build:
      context: ./backend
    image: backend:latest
    # ports:
    #   - "3000:3000"
    network_mode: "host"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27018:27017"