version: '3'
services:
  # angular-app:
  #   image: frontend
  #   ports:
  #     - "4200:4200"
  #   depends_on:
  #     - nodejs-app

  nodejs-app:
    image: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"